### PR TITLE
fixup! changed: redo restarting support

### PR DESCRIPTION
**Pull request by kmokstad**
How about this as an alternative to your last commit (the restart-preparsing stuff)?

Then the restartFile/Step variables are members of SIMSolver and are parsed by its parse method, instead of passing them as function arguments. Also the restart() method is now a member.
Haven't tested, just a question on the concept.

### CODE REVIEW

**Comment by akva2** [comment]
it's fine in pricinciple, but it still doesn't solve the problem that made me choose to use preparsing in the first place - i want a command line parameter in addition. i insist on having that, if only to avoid the need for two separate input files for the tests using this.

if we are already making this an "official"  part of the simulator API with virtual functions and all that jazz, we may as well lift the parsing to SIMoptions where we have this functionality.

**Comment by kmokstad** [comment]
Yes, I think it is even better to put it in SIMoptions, if you want to have the command-line option also (I didn't know that was crucial, thought you did not like the command-line options in the first place, that's why the preparsing stuff was introduced). It fits better in SIMoptions, since this is on the same generic level as the simulation output (VTF and HDF5) specifications, which already are there.

**Comment by kmokstad** [comment]
Like in this last commit (still not tested, since I don't have the CEREAL lib).

**Comment by akva2** [comment]
never said i disliked command line options, i just dislike them being the only way to go about it. winnie the pooh style :) preparsing is basically the same concept as SIMoptions, only for app specifics.

looks good.

and just fyi/in case; cereal is just an apt-get install libcereal-dev.

**Comment by kmokstad** [comment]
Right! Fint med ja takk begge deler. Har oppdatert committene noe og testa det nå med cereal installert. Ser ut til å fungere bra. La også til info i README.md om restart support. Har også gjort fixup's på de respektive app-ene som påvirkes av dette, men ikke laget separate PR's på disse. Kan gjøre det også hvis du vil (dvs. at du er enig i dette). Men du finner uansett branchene hos kmokstad med samme navn.

**Comment by akva2** [comment]
sure, jeg trenger ikke pr, jeg plukker rett fra branchene så fort jeg får dette på toppen av agendaen igjen.

**Comment by akva2** [comment]
this is now merged.

**Pull request closed without merging**
